<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenRender.Scene\OpenRender.Scene.csproj" />
    <ProjectReference Include="..\OpenRender.Rendering\OpenRender.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Assimp" Version="2.21.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
