<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenRender.Tools\OpenRender.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Core" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.21.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
